services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always
  vue-app:
    build:
      context: .
      dockerfile: ./docker/joellesite.Dockerfile
    container_name: JoelleVue
    restart: always
    ports:
      - '3000:3000'
    networks:
      - mynetwork
volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
